name: Update gist with WakaTime stats with customlization

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    name: Update Readme with Metrics
    steps:
      - uses: anmol098/waka-readme-stats@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 813c121301d1bac00df0108b0c43bd69
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
